export const questions = [
  'I am thorough in the things that I do.',
  'God has called me to start new churches or parachurch organizations to reach people who don’t know Jesus.',
  'I can sometimes help people understand the spiritual source of their problems.',
  'I make sure to tell someone “good job” if he or she did something well.',
  'When I share the Gospel message with unbelievers I either plant seeds, water seeds that others have planted, or harvest – leading a person to accept Jesus as their personal Savior.',
  'I believe with all my heart that “With God all things are possible.”',
  'I have prayerfully determined an amount of money to give to my church and do so faithfully, even when the economy is bad.',
  'God has used me as his instrument to instantaneously cure a sick or suffering person.',
  'I find something that needs to get done and do it without being asked.',
  'When someone speaks in tongues (i.e., an unknown language), God gives me an interpretation to share with my fellow Christians.',
  'The Holy Spirit supernaturally gives me information that just “pops” into my head.',
  'I get frustrated when no one is in charge.',
  'I have great compassion for those who are hurting.',
  'I have spoken God’s truth and performed a miracle to authenticate my message.',
  'The Lord sometimes speaks a corrective word through me to someone who is engaged in sinful behavior, warning them to repent.',
  'I have compassion for Christians caught in the snare of sin and want to protect them from Satan’s temptations.',
  'People have told me that I am effective at explaining biblical truth.',
  'When I pray to God I sometimes use a special “prayer language” that I do not know.',
  'I often ask the Spirit for wisdom for how to apply biblical truth in different situations, and Christians consider my advice to be helpful.',
  'When a team is planning an event or program I anticipate potential problems that may arise.',
  'I launched a ministry or church, and then I left it in the capable hands of others and went on to start something new.',
  'I am able to sense the presence of evil in a person or situation.',
  'I enjoy cheering up a person when he or she is “down in the dumps”.',
  'Some people have responded to my ministry by praying for salvation.',
  'God has advanced His Kingdom a lot when I believed that He would.',
  'I try to give money or material goods in a way that does not draw attention to myself.',
  'People are supernaturally healed by God as a result of my prayers.',
  'I see spiritual significance in doing the routine tasks in ministry.',
  'God’s name is glorified when He uses me to interpret the message of someone speaking in tongues.',
  'When reading and studying the Bible I discover important truths.',
  'I have the natural ability to influence others.',
  'I “do good anyway” and help people even when they do not deserve it.',
  'God has performed supernatural wonders and signs through me.',
  'When the Lord seems to be giving me a message to give to others, I apply Scriptural tests to make sure that it is from him.',
  'Caring for others comes naturally to me.',
  'I enjoy explaining things like theology or the Bible to people so they grow in their relationship with God.',
  'When I speak in tongues, the message strengthens my fellow Christians.',
  'The Holy Spirit shows me see clear solutions to complex problems.',
  'If someone has an idea I am able to think of the steps needed to turn that vision into a reality.',
  'Church leaders respect me as an authority in spiritual matters.',
  'I sometimes see or sense the presence of good or bad spiritual beings.',
  'When others are discouraged I come alongside them and use my words to reassure them.   ',
  'I am able to communicate the gospel to others in a clear and effective manner.',
  'I find it easy to trust God in situations when things do not look good from a human perspective.',
  'I do not give God the “leftovers” of my money; I give Him my “first fruits.”',
  'God has used me in a supernatural way to heal someone emotionally, spiritually, or physically.',
  'I volunteer my time doing the everyday tasks that are not very glamorous but need to get done.',
  'I have heard a Christian speak in tongues and been able to supernaturally translate it into English.',
  'Fellow Christians seek my perspective in an area of the Bible or theology.',
  'I motivate others to perform to the best of their ability.',
  'I can see past physical handicaps and realize that a person with special needs matters to God.',
  'Things I have done by the power of God have no natural explanation.',
  'The Holy Spirit has led me to boldly point out societal trends or teachings that contradict biblical principles.',
  'I have genuine concern for the well-being of my fellow Christians.',
  'When a pastor is giving a sermon I think of ways he could better communicate a certain point in his message.',
  'I or other Christians with the gift of “interpretation” have deciphered my messages from the Lord in tongues.  The messages built up the body of Christ.',
  'Fellow Christians ask my advice about their emotional or spiritual problems.',
  'I enjoy organizing ideas, people, and programs.',
  'I am culturally sensitive both within my own country and abroad.',
  'The Lord has led and empowered me to rebuke evil spirits.',
  'If a person is taking a step of faith I cheer him or her on.',
  'Depending on the need of the unbeliever I adapt my gospel presentation to show how Jesus meets that particular need.',
  'I challenge others to have a “bigger” view of God; that He is “bigger” than whatever struggles they are going through.',
  'I give above and beyond my church’s giving plan; giving more than 10% of my income to the Kingdom of God.',
  'I have used supernatural healings to authenticate God’s message to unbelievers.',
  'I am there to “lend a helping hand” in whatever needs to be done.',
  'When I interpret a message in tongues, the church is strengthened as a result.',
  'I have a regimented plan for reading and studying the Bible.',
  'I am able to cast a vision to others and they jump on board.',
  'I enjoy visiting the lonely and forgotten people in homeless shelters, nursing homes, and prisons.',
  'God’s name is glorified when he uses me to perform supernatural acts.',
  'The Holy Spirit has given me messages to give to people resulting in their strengthening, encouragement, and comfort.',
  'I enjoy giving guidance and direction to a small group of Christians.',
  'I can present a complex biblical or theological truth in a way that makes it easy to grasp.',
  'God has given me messages to communicate to his people and I have done so in a language unknown to me. The messages were edifying to them.',
  'When there is conflict or confusion in a situation, I pray for wisdom, and then I am able to offer sound advice.',
  'I think of better, more efficient ways to do things.',
  'I left or was sent out by my “home church” and have started at least one church or ministry in a different context or country. I have a vision for more.',
  'People describe me as perceptive of spiritual things or beings.',
  'I motivate others with my words to grow in the ministry God has called them to.',
  'When talking to unbelievers I try to steer the conversation so we talk about spiritual things.',
  'When God leads me in a specific direction, I move forward even if other Christians or nonbelievers oppose me.',
  'When there is a financial need somewhere in God’s Kingdom I am the first one in line with my checkbook.',
  'I find great joy in praying for the sick because God uses my prayers to supernaturally heal people.',
  'Doing things “behind the scenes” and not receiving praise is fine with me.',
  'When I interpret a message spoken in tongues my words are prophetic in nature.',
  'When I think about other people, God supernaturally reveals something about them that I did not know before.',
  'I set goals and then motivate and inspire people to work together to accomplish these goals for God’s glory.',
  'I enjoy bringing hope to people who have no hope.',
  'I believe miraculous acts go hand in hand with proclaiming the gospel.',
  'Other believers recognize that the Lord sometimes speaks through me to them with a specific message.',
  'I am “there” for people who need someone to talk with.',
  'I like to help others become good teachers.',
  'Speaking in tongues has made me more intimate with God.',
  'I am amazed at the wisdom that the Spirit gives me to attack problems and find the best solution.',
  'I clarify goals and create strategies to accomplish them.',
  'I have had a leading role in starting a new church or parachurch ministry, and have a vision for more.',
  'I recognize teaching or preaching that strays from biblical truth.',
  'If a person is going through a time of trial, I confirm that God is in control and He will work it out for good.',
  'I build relationships with non-Christians with the hope that I can share Gospel with them.',
  'I’ve seen God do amazing things when I put my complete trust in Him to act.',
  'If I see someone in need I help him or her out in whatever way possible.',
  'God’s name is glorified when He uses me to supernaturally heal others.',
  'I do not have a lot of unique talents but I want God to use me in whatever way possible.',
  'I am able to understand people when they speak in tongues.',
  'When I share insights God has given me about a particular Bible passage, my fellow Christians are strengthened.',
  'When I join a group I naturally take charge.',
  'I patiently support people going through painful or difficult life experiences and desire to help them get through it.',
  'Others can testify that I have been God’s instrument in bringing supernatural change in their lives.',
  'I have the ability to sense what God wants to communicate to people at a particular time or situation.',
  'I enjoy nurturing others toward full devotion to Jesus Christ.',
  'I spend time studying the Bible because I understand the awesome responsibility a person has in accurately communicating God’s Word.',
  'When I speak in tongues, I think I am worshipping Jesus.',
  'I am able to apply my knowledge in practical and helpful ways.',
]
